// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace examenParcial2
{
	public partial class dadasd : UITableView
	{
		public dadasd (IntPtr handle) : base (handle)
		{
		}
	}
}
